function raschet()
    // Задаем константы
    re = 6371000;
    k = 1.38*(10^(-23));
    // Получаем значения переменных величин из полей данных
    // Координаты БпЛА
    h2 = evstr(get(HeightUAVEdit, 'string')); // высота
    phi2 = evstr(get(LatitudeUAVEdit, 'string')); // широта
    lam2 = evstr(get(LongitudeUAVEdit, 'string')); // долгота
    // Координаты Наземной станции
    h1 = evstr(get(HeightGroundStationEdit, 'string')); // высота
    phi1 = evstr(get(LatitudeGroundStationEdit, 'string')); // широта
    lam1 = evstr(get(LongitudeGroundStationEdit, 'string')); // долгота
    // Остальные параметры
    f = evstr(get(FreqEdit, 'string')); // Рабочая частота
    g1 = evstr(get(gainUAVEdit, 'string')); // Коэффициент усиления антенны БпЛА
    g2 = evstr(get(gainGroundStationEdit, 'string')); // Коэффициент усиления антенны наз. ст.
    b = evstr(get(FreqSpectrEdit, 'string')); // Спектр рабочих частот
    t = evstr(get(tempEdit, 'string')); // Температура окружающией среды
    pt = evstr(get(PowerEdit, 'string')); // Мощность передатчика
    osh = evstr(get(SNRStationEdit, 'string')); // Отношение сигнал-шум
    
    // Приводим все данные к нормальному виду
    f = f * 10^6; // МГц в Гц
    b = b * 10^3; // кГц в Гц
    t = t + 273.15; // Цельсии в Кельвины
    rad = 3.14 / 180;
    phi1 = phi1 * rad; // Градусы в радианы
    phi2 = phi2 * rad; // Градусы в радианы
    lam1 = lam1 * rad; // Градусы в радианы
    lam2 = lam2 * rad; // Градусы в радианы
    g1 = 10^(g1/10); // Из дБ в разы
    g2 = 10^(g2/10); // Из дБ в разы
    
    // Находим dx, dy, dz
    dx = cos(phi2)*cos(lam2)-cos(phi1)*cos(lam1);
    dy = cos(phi2)*sin(lam2)-cos(phi1)*sin(lam1);
    dz = sin(phi2)-sin(phi1);

    // Находим длинну хорды
    c = sqrt(dx^2+dy^2+dz^2)*re;
    // Определяем разницу высот между антеннами
    dh = abs(h2-h1);
    
    // Находим расстояние между наземной станцией и БпЛА
    d = sqrt((dh^2)+(c^2));
    
    // Длинна волны для рабочей частоты
    lam3 = 300000000/f;
    
    // Вычисляем мощность приходящего сигнала
    nominator = pt*g1*g2*lam3^2; // В РАЗЫ НЕ В ДЕЦИБЕЛАХ
    denominator = (4*3.14*d)^2;    
    pr = nominator/denominator;
    
    // Вычисляем степень затухания
    l = pt/pr;
    // Переводим степень затухания в дБ
    l = 10*log10(l);
    
    // Определяем мощность Шума
    pshuma = k*t*b;
    // ОТНОШЕНИЕ СИГНАЛ ШУМ

    snr = pr/pshuma;
    // Переводим в дБ
    snr = 10*log10(snr);
    
    // Сравниваем заданные значения OSH и SNR
    // и выдаем результат
    if snr > osh
        // Result
        ResultLabel = uicontrol(mainWindow, ...
        "Style","text",...
        "String","РЕЗУЛЬТАТ :",...
        "units", "normalized", ...
        "tag", "result", ...
        "position", [0.35 0.05 0.2 0.1]);

        ResultValueLabel = uicontrol(mainWindow, ...
        "Style","text",...
        "String", string(snr),...
        "units", "normalized", ...
        "position", [0.5 0.05 0.05 0.1]);
        ResultLabel.fontSize = 20;
        ResultValueLabel.fontSize = 20;
        ResultLabel.BackgroundColor = [0.8,0.99,0.8];
        ResultValueLabel.BackgroundColor = [0.8,0.99,0.8];
    else
        // Result
        ResultLabel = uicontrol(mainWindow, ...
        "Style","text",...
        "String","РЕЗУЛЬТАТ :",...
        "units", "normalized", ...
        "tag", "result", ...
        "position", [0.35 0.05 0.2 0.1]);

        ResultValueLabel = uicontrol(mainWindow, ...
        "Style","text",...
        "String", string(snr),...
        "units", "normalized", ...
        "position", [0.5 0.05 0.05 0.1]);
        ResultLabel.fontSize = 20;
        ResultValueLabel.fontSize = 20;
        ResultLabel.BackgroundColor = [0.5,0.5,0.5];
        ResultValueLabel.BackgroundColor = [0.5,0.5,0.5];
    end
    
endfunction

mainWindow = createWindow();
mainWindow.figure_name = "Расчет энергетики радиолинии";
mainWindow.BackgroundColor = [0.85,0.93,1];
mainWindow.Position = [0,0,1000,700];
//mainWindow.Position = [100,100,max,max];
xlfont("Monospaced",10);

SystemParamTitle = uicontrol(mainWindow, ...
"style","text",...
"string","Основные параметры системы",...
"fontSize", 18, ...
"horizontalAlignment","center",...
"ForegroundColor", [0.0,0,0], ...
"units", "normalized", ...
"position", [0.02 0.9 0.45 0.05]);
//SystemParamTitle.font_style = 0;

//частота
FreqLabel = uicontrol(mainWindow, ...
"style","text",...
"string","Рабочая частота (МГц)",...
"units", "normalized", ...
"position", [0.02 0.8 0.25 0.035]);
FreqEdit=uicontrol(mainWindow, ...
"style", "edit",...
"string", "100",...
"horizontalAlignment","right",...
"units", "normalized", ...
"tag", "freq_input", ...
"position", [0.3 0.8 0.125 0.035]);

//Мощность передатчика
PowerLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Мощность передатчика (Вт)",...
"units", "normalized", ...
"position", [0.02 0.73 0.25 0.035]);
PowerEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "100",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "pwr_input", ...
"position", [0.3 0.73 0.125 0.035]);

//gain беспилотника
gainUAVLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Усиление антенны БПЛА (дБ)",...
"units", "normalized", ...
"position", [0.02 0.66 0.25 0.035]);
gainUAVEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "1",...
"tag", "gain_air", ...
"HorizontalAlignment","right",...
"units", "normalized", ...
"position", [0.3 0.66 0.125 0.035]);

//gain наземной станции
gainGroundStationLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Усиление антенны наземной станции (дБ)",...
"units", "normalized", ...
"position", [0.02 0.59 0.25 0.035]);
gainGroundStationEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "1",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"position", [0.3 0.59 0.125 0.035]);

//Спектр частот
FreqSpectrLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Спектр частот (КГц)",...
"units", "normalized", ...
"position", [0.5 0.8 0.3 0.035]);
FreqSpectrEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "20",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "spector_freq", ...
"position", [0.85 0.8 0.1 0.035]);

//Температура
tempLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Температура (по Цельсию)",...
"units", "normalized", ...
"position", [0.5 0.73 0.3 0.035]);

tempEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "50",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag","tempreger",...
"position", [0.85 0.73 0.1 0.035]);

//SNR
SNRLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Отношение сигнал-шум (дБ)",...
"units", "normalized", ...
"position", [0.5 0.66 0.3 0.035]);
SNRStationEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "5",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag","snr_input",...
"position", [0.85 0.66 0.1 0.035]);

//кнопка начать расчет
startButton = uicontrol(mainWindow, ...
"Style","pushbutton",...
"String","Начать расчет",...
"fontSize", 18, ...
"tag", "Start", ...
"callback" , "raschet", ...
"ForegroundColor", [0.0,0,0], ...
"units", "normalized", ...
"position", [0.3 0.22 0.3 0.035]);

//лейбл координаты БПЛА
UAVCoordparamTitle = uicontrol(mainWindow, ...
"style","text",...
"string","Координаты БпЛА",...
"fontSize", 18, ...
"horizontalAlignment","center",...
"ForegroundColor", [0.0,0,0], ...
"units", "normalized", ...
"position", [0.5 0.49 0.45 0.035]);

//лейбл координаты наземной станции
GroundStationCoordparamTitle = uicontrol(mainWindow, ...
"style","text",...
"string","Координаты наземной станции",...
"fontSize", 18, ...
"horizontalAlignment","center",...
"ForegroundColor", [0.0,0,0], ...
"units", "normalized", ...
"position", [0.02 0.49 0.45 0.035]);
//

//Широта наземной станции
LatitudeGroundStationLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Широта (градусы)",...
"units", "normalized", ...
"position", [0.02 0.42 0.25 0.035]);
LatitudeGroundStationEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "13",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "s_stanciy", ...
"position", [0.3 0.42 0.125 0.035]);

//Долгота наземной станции
LongitudeGroundStationLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Долгота (градусы)",...
"units", "normalized", ...
"position", [0.02 0.35 0.25 0.035]);
LongitudeGroundStationEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "13",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "d_stanciy", ...
"position", [0.3 0.35 0.125 0.035]);

//Высота наземной станции
HeightGroundStationLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Высота (метры)",...
"units", "normalized", ...
"position", [0.02 0.28 0.25 0.035]);
HeightGroundStationEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "50",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "v_stanciy", ...
"position", [0.3 0.28 0.125 0.035]);

//Широта БПЛА
LatitudeUAVLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Широта (градусы)",...
"units", "normalized", ...
"position", [0.5 0.42 0.3 0.035]);
LatitudeUAVEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "15",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "s_bpla", ...
"position", [0.85 0.42 0.1 0.035]);

//Долгота БПЛА
LongitudeUAVLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Долгота (градусы)",...
"units", "normalized", ...
"position", [0.5 0.35 0.3 0.035]);
LongitudeUAVEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "15",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "d_bpla", ...
"position", [0.85 0.35 0.1 0.035]);

//Высота БПЛА
HeightUAVLabel = uicontrol(mainWindow, ...
"Style","text",...
"String","Высота (метры)",...
"units", "normalized", ...
"position", [0.5 0.28 0.3 0.035]);
HeightUAVEdit=uicontrol(mainWindow, ...
"Style", "edit",...
"String", "100",...
"HorizontalAlignment","right",...
"units", "normalized", ...
"tag", "v_bpla", ...
"position", [0.85 0.28 0.1 0.035]);

// Цветовые стили
SystemParamTitle.BackgroundColor = [0.74,0.84,1];
GroundStationCoordparamTitle.BackgroundColor = [0.74,0.84,1];
UAVCoordparamTitle.BackgroundColor = [0.74,0.84,1];

startButton.BackgroundColor = [0.68,0.78,1];
ContactButton.BackgroundColor = [0.74,0.82,0.89];

FreqLabel.BackgroundColor = [0.8,0.89,1];
PowerLabel.BackgroundColor = [0.8,0.89,1];
gainUAVLabel.BackgroundColor = [0.8,0.89,1];
gainGroundStationLabel.BackgroundColor = [0.8,0.89,1];

FreqSpectrLabel.BackgroundColor = [0.8,0.89,1];
tempLabel.BackgroundColor = [0.8,0.89,1];
SNRLabel.BackgroundColor = [0.8,0.89,1];
HeightGroundStationLabel.BackgroundColor = [0.8,0.89,1];
HeightUAVLabel.BackgroundColor = [0.8,0.89,1];
LatitudeGroundStationLabel.BackgroundColor = [0.8,0.89,1];
LatitudeUAVLabel.BackgroundColor = [0.8,0.89,1];
LongitudeGroundStationLabel.BackgroundColor = [0.8,0.89,1];
LongitudeUAVLabel.BackgroundColor = [0.8,0.89,1];


